import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Zap, Trash2 } from "lucide-react";
import { useEventStore } from "../stores/eventStore";
import EventRow from "./EventRow";
const EventFeed = () => {
    const { events, clear, connected } = useEventStore();
    return (_jsxs("div", { className: "bg-white rounded-3xl overflow-hidden flex flex-col h-[600px]", style: { border: "1px solid var(--color-border)" }, children: [_jsxs("div", { className: "px-7 py-5 flex items-center justify-between", style: { borderBottom: "1px solid var(--color-border)" }, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `p-2 rounded-xl ${connected ? "bg-amber-50" : "bg-zinc-100"}`, children: _jsx(Zap, { className: `w-5 h-5 ${connected ? "text-amber-600" : "text-zinc-400"}` }) }), _jsx("h2", { className: "text-lg font-extrabold tracking-tight", style: { color: "var(--color-heading)" }, children: "Live Feed" })] }), _jsx("button", { onClick: clear, className: "p-2.5 hover:bg-zinc-100 rounded-xl transition-colors", style: { color: "var(--color-muted)" }, title: "Clear Feed", children: _jsx(Trash2, { className: "w-4 h-4" }) })] }), _jsxs("div", { className: "flex-1 overflow-auto p-5 space-y-3", children: [!connected && (_jsxs("div", { className: "flex flex-col items-center justify-center h-full space-y-4 text-center", children: [_jsx("div", { className: "p-5 bg-zinc-50 rounded-2xl", children: _jsx(Zap, { className: "w-10 h-10 text-zinc-200 animate-pulse" }) }), _jsx("p", { className: "text-[11px] uppercase tracking-[0.15em] font-bold", style: { color: "var(--color-muted)" }, children: "Connecting to live stream..." })] })), connected && events.length === 0 && (_jsxs("div", { className: "flex flex-col items-center justify-center h-full space-y-4 text-center", children: [_jsx("div", { className: "p-5 bg-zinc-50 rounded-2xl", children: _jsx(Zap, { className: "w-10 h-10 text-zinc-200" }) }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("p", { className: "text-[11px] font-bold uppercase tracking-[0.15em]", style: { color: "var(--color-muted)" }, children: "Monitoring activity" }), _jsx("p", { className: "text-[11px] max-w-[180px] leading-relaxed", style: { color: "var(--color-muted)" }, children: "Evaluation events will appear here in real-time." })] })] })), events.map((event, idx) => (_jsx(EventRow, { event: event }, idx)))] })] }));
};
export default EventFeed;
