import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ScoreBadge from "./ScoreBadge";
const LeaderboardTable = ({ entries }) => {
    return (_jsxs("table", { className: "w-full text-left border-collapse", children: [_jsx("thead", { children: _jsxs("tr", { style: { borderBottom: "1px solid var(--color-border)" }, children: [_jsx("th", { className: "px-7 py-4 text-[10px] font-bold uppercase tracking-[0.12em]", style: { color: "var(--color-muted)" }, children: "Rank" }), _jsx("th", { className: "px-7 py-4 text-[10px] font-bold uppercase tracking-[0.12em]", style: { color: "var(--color-muted)" }, children: "Agent" }), _jsx("th", { className: "px-7 py-4 text-[10px] font-bold uppercase tracking-[0.12em] text-center", style: { color: "var(--color-muted)" }, children: "Score" }), _jsx("th", { className: "px-7 py-4 text-[10px] font-bold uppercase tracking-[0.12em] text-right", style: { color: "var(--color-muted)" }, children: "Seed" }), _jsx("th", { className: "px-7 py-4 text-[10px] font-bold uppercase tracking-[0.12em] text-right", style: { color: "var(--color-muted)" }, children: "Submitted" })] }) }), _jsx("tbody", { children: entries.map((entry, idx) => (_jsxs("tr", { className: "group hover:bg-zinc-50/80 transition-colors tabular-nums", style: { borderBottom: "1px solid var(--color-border)" }, children: [_jsx("td", { className: "px-7 py-5", children: idx < 3 ? (_jsx("span", { className: `
                    inline-flex items-center justify-center w-7 h-7 rounded-lg text-xs font-extrabold
                    ${idx === 0 ? "bg-amber-50 text-amber-600" : ""}
                    ${idx === 1 ? "bg-zinc-100 text-zinc-500" : ""}
                    ${idx === 2 ? "bg-orange-50 text-orange-500" : ""}
                  `, children: entry.rank })) : (_jsx("span", { className: "text-sm font-semibold pl-2", style: { color: "var(--color-muted)" }, children: entry.rank })) }), _jsx("td", { className: "px-7 py-5", children: _jsx("span", { className: "font-semibold group-hover:text-zinc-900 transition-colors", style: { color: "var(--color-heading)" }, children: entry.agent_name }) }), _jsx("td", { className: "px-7 py-5 text-center", children: _jsx(ScoreBadge, { score: entry.score }) }), _jsx("td", { className: "px-7 py-5 text-right text-sm font-mono", style: { color: "var(--color-muted)" }, children: entry.seed }), _jsx("td", { className: "px-7 py-5 text-right text-xs", style: { color: "var(--color-muted)" }, children: new Date(entry.submitted_at).toLocaleDateString() })] }, idx))) })] }));
};
export default LeaderboardTable;
